### ISSUE TITLE
Can't find source of AbiBinaryGenTransactionWriter

### ISSUE THREAD

**Issue by ttoommbb** [memtrip/eos-jvm#1]
I tend to convert transaction object into buffer as eosjs did:
`rawTx.context_free_actions = arg.context_free_actions;
            rawTx.actions = arg.actions;
            rawTx.transaction_extensions = arg.transaction_extensions;

            // Resolve shorthand
            txObject = Transaction.fromObject(rawTx);
            // console.log('txObject', txObject)

            buf = Fcbuffer.toBuffer(Transaction, txObject);`

Before impl by my self I found your project, there's a missing class that I assume it contains the logical I need.

**Comment by samkirton** [comment]
AbiBinaryGenTransactionWriter is a boilerplate class that is  auto generated by the [eos-abi-writer](https://github.com/memtrip/eos-jvm/tree/master/eos-abi-writer) module. An `AbiBinaryGen*Writer` class is generated for an interface that is annotated with `@AbiWriter`. The README in the [eos-abi-writer](https://github.com/memtrip/eos-jvm/tree/master/eos-abi-writer) has further steps you can follow. You can join us on Telegram if you need more help.
