### ISSUE TITLE
#BUG - SENSITIVE DATA LEAK (PRIVATE KEY HAS BEEN LEAKED)

### ISSUE THREAD

**Issue by Abdelkad3r** [memtrip/eos-jvm#10]
check out: https://github.com/memtrip/eos-jvm/blob/5e2465a1f186b3e18f50294b0579b0e17a30f4d4/eos-core/src/test/kotlin/com/memtrip/eos/core/crypto/EosKeyTests.kt

there is a leaked private key!

**Comment by samkirton** [comment]
The private key was generated for test purposes, it isn't linked to a production account.
