### ISSUE TITLE
Transfer memo gets cut off with Cyrillic letters

### ISSUE THREAD

**Issue by ysoftware** [memtrip/eos-jvm#4]
I'm not sure why, but transfer memo gets cut off when cyrillic letters are present.
String in memory doesn't get cut off, so it's probably something to do with `DefaultByteWriter`'s method `fun putString(value: String)`.

Here are examples of incorrect transactions:

expected: тест
actual: **те**
[trx link](https://eosflare.io/tx/9A93B35C2A6943A89676575DB4150AB0BCDA888BB6C037BBE8AB1C109A527130)

expected: тестируем testing 1234567890
actual: **тестируем testing 1**
[trx link](https://eosflare.io/tx/A4A950FE4D4C6C8E13E3CB792C581E29C2F41A23865A159128109C50C6CEAEB9)

**Comment by samkirton** [comment]
I reproduced the issue with the following tests
```
       on("transfer abi model with Cyrillic letters") {

            val transferArgs = TransferArgs(
                "memtripissu5",
                "memtripblock",
                "12.3040 EOS",
                "тест"
            )
            val transferBody = TransferBody(transferArgs)

            val output = transactionWriter.squishTransferBody(transferBody).toHex()

            it("should encode letters correctly as hex") {
                assertEquals("5034c6aeba9ba59200118da7ba9ba592a0e001000000000004454f530000000008d182d0b5d181d182", output)
            }
        }

        on("transfer abi model with Cyrillic letters 2") {

            val transferArgs = TransferArgs(
                "memtripissu5",
                "memtripblock",
                "12.3040 EOS",
                "тестируем testing 1234567890"
            )
            val transferBody = TransferBody(transferArgs)

            val output = transactionWriter.squishTransferBody(transferBody).toHex()

            it("should encode letters correctly as hex") {
                assertEquals("5034c6aeba9ba59200118da7ba9ba592a0e001000000000004454f530000000025d182d0b5d181d182d0b8d180d183d0b5d0bc2074657374696e672031323334353637383930", output)
            }
        }
```

**Comment by samkirton** [comment]
This is fixed in `beta01`. 

The following tests verify the bug fix:
- [End to end transfer on Jungle net](https://github.com/memtrip/eos-jvm/blob/master/eos-chain-actions/src/test/kotlin/com/memtrip/eos/chain/actions/transaction/TransferChainTest.kt#L140)
- [Byte writing](https://github.com/memtrip/eos-jvm/blob/master/eos-abi-writer/src/test/kotlin/com/memtrip/eos/abi/writer/StringWriterTests.kt#L43)
